### PR TITLE
Accessibility: mark up .input-button as semantic buttons

### PR DESCRIPTION
**Pull request by imgiseverything**
As described here: https://github.com/OvidijusParsiunas/deep-chat/issues/286 the 'button's coded into deep-chat are not semantic buttons and as such are accessible to keyboard/switch users nor screen-reader users.

## role="button"
This PR adds the semantic `role` attribute with the `value` of `button` to the `.input-button` elements so it announces to screen-readers that it is a button.

## Disabled buttons
It also adds other semantics such as `aria-disabled="true"` instead of  just styling the buttons to look _disabled_ so screen-reader users hear when the button is disabled

_Note_: rather than having `aria-disabled="false"` when the button is enabled, instead we remove the attribute

## Loading/busy buttons
It also adds other semantics such as `aria-busy="true"` instead of  just styling the buttons to look _busy_ so screen-reader users hear when the button is loading.

_Note_: rather than having `aria-busy="false"` when the button is not busy, instead we remove the attribute

## Keyboard/Switch accessibility
- Tabindex of 0 is added so non-mouse users can tab to the buttons before interacting with them.
- `:hover` styles in CSS are duplicated for :focus-visible so non-mouse users can see when the button is in focus.

### CODE REVIEW

**Review by OvidijusParsiunas — APPROVED** [review]

**Comment by OvidijusParsiunas** [comment]
Hey @imgiseverything!
That looks amazing!

The code looks great!
There still seems to be one area where you haven't edited the buttons. That is the modal buttons. Currently, Deep Chat provides two kids of modals; [infoModal](https://deepchat.dev/docs/files/#InfoModal) and the [camera](https://deepchat.dev/docs/files/#camera) modal. Both of these modals add their buttons via the [`addButtons`]() method. If you don't mind, could you add the necessary attributes to the buttons inside the `forEach` loop (as I think they would all be the same). I would do it myself, however I am not an expert on this, hence if you could it that would be amazing!

Let me know if you need any help, thankyou!

**Comment by OvidijusParsiunas** [comment]
Hi @imgiseverything. Since I am going to release the next version of Deep Chat very shortly, I have merged your changes and make the necessary updates that I mentioned myself. 
Thankyou for your work! It is very much appreciated!

**Comment by imgiseverything** [comment]
@OvidijusParsiunas Thanks Ovidijus. Sorry for the slow reply! I will look into my other accessibility issues now to see if I can implement them as a PR for you :) 

see: https://github.com/OvidijusParsiunas/deep-chat/issues/285

**Comment by OvidijusParsiunas** [comment]
Thankyou!

I kept the issues open as I was going to take care of them myself eventually. Your helps is always appreciated!

**Pull request merged**
