### PR TITLE
Azure OpenAI Assistants API support

### LINKED ISSUE #239: Azure OpenAI Assistants API
Has anyone tried deep-chat with [Azure Assistants API](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/assistant)? I'm in the process of getting an Azure OpenAI account setup, and thought I'd ask to see if deep-chat supports it.

Looks like MS has an NPM package for it too:
https://learn.microsoft.com/en-us/javascript/api/overview/azure/openai-readme?view=azure-node-preview

### PR DESCRIPTION
**Pull request by bruffridge**
This PR adds support for the Azure OpenAI Assistants API. Fixes #239 

```
    <deep-chat
      id="chat-element"
      directConnection='{
        "azureOpenAI": {
          "key": "YOUR_AZURE_KEY",
          "validateKeyProperty": true,
          "azureConfig": {
            "endpoint": "https://YOUR_RESOURCE_NAME.openai.azure.com",
            "version": "2024-05-01-preview"
          },
          "assistant": {
            "new_assistant": {
              "model": "gpt-4o",
              "name": "Test Azure Assistant",
              "description": "An assistant to test Azure integration into deep-chat",
              "instructions": "You are an assistant. Your instructions are to help test the integration of Azure with deep-chat",
              "tools": [
                { "type": "code_interpreter" },
                { "type": "file_search" }
              ]
            },
            "files_tool_type": "code_interpreter"
          }
        }
      }'
    ></deep-chat>
```

### CODE REVIEW

**Comment by OvidijusParsiunas** [comment]
Hey @bruffridge.

I can see you were busy. Thankyou for raising this PR. I am unfortunately just about to leave for a trip due to a long weekend here in Japan, so my availability might be a little limited. But I'll take a look at this PR.

Having briefly looked at the code, a lot of it appears to be very similar to the existing OpenAIChat/OpenAIAssistant code (which is great), and I am wondering if instead of repeating the code - we could try to reuse the existing code by extending it and have Azure be inside concrete classes. This way we can keep the addition of new code to a minimum and the overall bundle size smaller.

I know this may sound a little complicated and I can probably do it myself, if you could instead perhaps tell me the areas where you really had to make explicit changes for Azure (instead of copying) and I'll minimize the code myself.

Thanks for the PR again and apologies for the delays in everything as I have just moved countries and am playing catchup with all of my GitHub projects.

**Comment by OvidijusParsiunas** [comment]
Hey @bruffridge.
I have attempted to edit the code in your repository but was unable to due to me not having _writer_ permissions.
Your code is really nice, but the main problem is what I had mentioned in the previous comment - a lot of it is repeated and can be minimized by extending classes.

Due to me not having much free time recently I did not hesitate and start making the required changes right away (based on the code in your PR). The necessary changes for the basic OpenAI Chat via Azure are in the following [commit](https://github.com/OvidijusParsiunas/deep-chat/commit/6f2f4ab88133d54b54819dba1f016261d232e3c2).
I have made a small change to how the interface is exposed. Instead of creating an entirely new service, I placed the OpenAI Chat inside the [Azure](https://deepchat.dev/docs/directConnection/Azure) domain. The new Azure TS interface can be found [here](https://github.com/OvidijusParsiunas/deep-chat/commit/6f2f4ab88133d54b54819dba1f016261d232e3c2#diff-902c13d8a2f6c2e397d63a400c5342301f451832ed2c605b9503cf6a90af58bb).

This is what it looks like:
```
type URLDetails = {
  endpoint: string;
  version: string;
  deploymentId: string;
};

export interface AzureOpenAI {
  urlDetails: URLDetails;
  chat?: true | OpenAIChat;
  assistant?: true | OpenAIAssistant;
}

export interface Azure {
  openAI?: AzureOpenAI;
  ...
```

I am going to do the Assistants API on another day and publish it for you to try it.
Apologies for not using this PR which takes away the credit of your work, but the new code would have been possible without what you have done. So thankyou very much for that.

Because this PR is not going to be used I will be closing it.
Thankyou!

**Comment by OvidijusParsiunas** [comment]
Hi @bruffridge.

I have not published this change yet, my apologies. The reason for this is because my local codebase has a lot of experimental code which I don't want to publish and I am currently working on refactoring the assistants logic. I should have this all done pretty soon and will update you in this PR on the latest.

Thankyou!

**Comment by OvidijusParsiunas** [comment]
Hi @bruffridge.
I have released a new `deep-chat-dev` and `deep-chat-react-dev` package version `9.0.197`. This includes all of the refactored methods to access OpenAI API via Azure.

The new [azure](https://deepchat.dev/docs/directConnection/Azure#azure) interface looks as follows:

```
type URLDetails = {
  endpoint: string;
  version: string;
  deploymentId: string;
};

export interface AzureOpenAI {
  urlDetails: URLDetails;
  chat?: true | OpenAIChat;
  assistant?: true | OpenAIAssistant;
}

export interface Azure {
  openAI?: AzureOpenAI;
  textToSpeech?: AzureRegion & AzureTextToSpeechConfig;
  ...
}
```
The `chat` and `assistant` properties are exactly the same as the OpenAI [chat](https://deepchat.dev/docs/directConnection/OpenAI#Chat) and [assistant](https://deepchat.dev/docs/directConnection/OpenAI#Assistant) properties.

The way you would use this interface would be as follows:

```
directConnection = {
  azure: {
    openAI: {
      chat: true,
      urlDetails: {
        deploymentId: 'azure-deployment-id',
        endpoint: 'azure-endpoint',
        version: 'azure-resource-version',
      }
    }
  }
}
```

Let me know if you have any issues!

**Comment by bruffridge** [comment]
I updated to `deep-chat-dev` `9.0.198` but it didn't work. When I enter the API key into the text input it tries to validate the key by sending a request to `https://api.openai.com/v1/models` instead of the Azure endpoint. I tried putting the `key` and `validateKeyProperty` up a level in the `azure` object but that didn't work either.

```
directConnection={{
    azure: {
      openAI: {
        key: key,
        validateKeyProperty: key ? false : true,
        assistant: key ? {
          assistant_id: asstId,
          new_assistant: asstConfig,
          thread_id: threadId,
          load_thread_history: false,
          files_tool_type: fileTools,
          function_handler: handleFuncCalling
        } : null,
        urlDetails: {
          deploymentId: 'gpt-4o',
          endpoint: 'https://RESOURCE_NAME.openai.azure.com',
          version: '2024-08-01-preview'
        }
      }
    }
  }}
```

**Comment by bruffridge** [comment]
I'm shooting in the dark because I haven't done any debugging, but did you remember that the authorization mechanism differs between azure and openai?

## 2. API_KEY header change
Another difference is instead of setting the api-key as  `Authorization: Bearer OPENAI_API_KEY` header, in Azure it is set as a custom `api-key` header

```
curl https://YOUR_RESOURCE_NAME.openai.azure.com/openai/threads \
  -H "Content-Type: application/json" \
  -H "api-key: $AZURE_OPENAI_API_KEY" \
  -d ''
```

**Comment by OvidijusParsiunas** [comment]
Hey!
Apologies for the late reply! I merged your newest PR. Do the new code changes take care of the issues above? If not, please let me know! Thankyou!!

**Pull request closed without merging**
